### ISSUE TITLE
story: executor should be able to fetch job log for k8s cluster

### ISSUE THREAD

**Issue by yashipro13** [gopay-bootcamp/octavius#20]
#### Description
Executor should be able to fetch the logs of jobs executed by k8s cluster.

#### Present Behaviour
No such behaviour

#### Expected Behaviour
K8s cluster must send job logs to executor, as soon as execution of job completes.

**Comment by jasoet** [comment]
My plan is
1. Every execution must have an execution context. Execution context is metadata and information related to certain execution. Execution context must have a unique ID and have all of the information that can be used as an audit. 
2. In this sense, with an execution context, we will able to gather, analyze, and even reproduce the execution.
3. The job log is one of the information inside the Execution Context. 
4. Gathering job logs doesn't need to wait execution to be completed. Executor will fetch the log instead of K8s Cluster send the log to executor. For this we can see the implementation from Gopay Proctor.
