### ISSUE TITLE
fix: Adding error checks instead of using .Err

### ISSUE THREAD

**Issue by yashipro13** [gopay-bootcamp/octavius#40]
#### Description
As suggested by @faruqisan in PR #37 comments, a good design would be adding error check everywhere, wherever the error is being first occurring, instead of passing it into logger.Err .

Create a error check everywhere, and use logger.Error only if error is not nil, else log using Info.

#### Present Behaviour
Errors are being passed into logger.Error without a check if its nil or not. An internal check is being carried out in logger.Err

#### Expected Behaviour
Pass error in logger.Error only if error is not nil, and use Info elsewhere to log.

**Comment by faruqisan** [comment]
Thanks for opening the issue, added some reference:

- https://github.com/golang/go/wiki/CodeReviewComments#handle-errors
- https://golang.org/doc/effective_go.html#errors
- https://medium.com/@teivah/good-code-vs-bad-code-in-golang-84cb3c5da49d (premium content)

> Error management
The error management is kind of terrible the bad implementation.
We can find some cases where potential errors returned in the second argument are not even managed:
The good implementation deals with each potential error:

```go
preprocessed, err := preprocess(bytes)
if err != nil {
  return Message{}, err
}
```

>We can also find some mistakes in the bad implementation like in the following code:

```go
if len(in) == 0 {
  return "", fmt.Errorf("Input is empty")
}
```

>The first mistake is a syntax one. An error string shall neither be capitalized nor end with a punctuation according to Go standards.
The second mistake is due to the fact that if an error string is a simple constant (no formatting is required), a call to errors.New() is slightly more performant.
The good implementation looks like:
```go
if len(in) == 0 {
	return nil, errors.New("input is empty")
}
```

and also keep in mind that error should only returned OR logged.

**Comment by littlestar642** [comment]
closing because now already merged.
